site_name: STEAMtronix
site_url: https://docs.steamtronix.az/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
#    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: az
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Light mode    
      primary: blue
      accent: blue
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Dark mode
      primary: blue
      accent: blue 
  logo: assets/steamtronix-logo.png
  favicon: assets/steamtronix-lfavicon-512x512.png


plugins:
  - social
  - search
  - optimize


plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: az
          default: true
          name: Azərbaycan dili
          build: true
        - locale: en
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true


nav:
  - index.md       
  - nano/nano-edu.md


docs_dir: docs  # Root docs folder

# Additional MkDocs and theme configurations
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/steamtronix
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/steamtronix
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/steamtronix
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/steamtronix/
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@steamtronix
    - icon: fontawesome/brands/github
      link: https://github.com/steamtronix  


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://steamtronix.az/"  target="_blank" rel="noopener">STEAMtronix</a>
